services:
  database:
    build: src/main/resources/database/.
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sveta
      - POSTGRES_PASSWORD=sveta1234
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 9090:8080
volumes:
  pgdata:

# usage of adminer:
# http://localhost:9090
# for server fill in 'database'